name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Install dependencies
        run: sudo apt-get install libsqlite3-dev
      - name: Install bundler
        run: gem install bundler:1.17.2
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Run Tests
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Install rubocop
        run: gem install rubocop
      - name: Install rubocop-rspec
        run: gem install rubocop-rspec
      - name: Run rubocop
        run: rubocop
